In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("project.csv")
df

                        time  entry_id  temperature  humidity  co2ppm     type
0    2020-09-19 22:53:28 +06         1         32.0      90.0     927     Rain
1    2020-09-19 22:53:44 +06         2         32.0      90.0     928     Mist
2    2020-09-19 22:54:01 +06         3         32.0      92.0     925  Drizzle
3    2020-09-19 22:54:17 +06         4         32.0      93.0     929     Rain
4    2020-09-19 22:54:34 +06         5         32.0      93.0     930     Mist
..                       ...       ...          ...       ...     ...      ...
395  2020-09-23 13:45:54 +06       396         30.7      83.4     630  Drizzle
396  2020-09-23 13:46:14 +06       397         30.7      84.0     635     Rain
397  2020-09-23 13:46:29 +06       398         30.7      84.5     638  Drizzle
398  2020-09-23 13:46:50 +06       399         30.7      81.6     640     Rain
399  2020-09-23 13:47:05 +06       400         30.7      81.3     642  Drizzle

[400 rows x 6 columns]

In [3]:
reg = linear_model.LinearRegression()
reg.fit(df[['temperature','humidity']],df.co2ppm)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [4]:
reg.coef_

array([14.13234194, 17.52830402])

In [5]:
reg.intercept_

-1219.24355322225

In [6]:
reg.predict([[30.5, 85]])

array([701.69871756])

In [7]:
reg.predict([[32, 90]])

array([810.53875057])

In [8]:
x = df.drop(['time','entry_id','co2ppm','type'], axis='columns')
x

     temperature  humidity
0           32.0      90.0
1           32.0      90.0
2           32.0      92.0
3           32.0      93.0
4           32.0      93.0
..           ...       ...
395         30.7      83.4
396         30.7      84.0
397         30.7      84.5
398         30.7      81.6
399         30.7      81.3

[400 rows x 2 columns]

In [9]:
y = df.co2ppm
y

0      927
1      928
2      925
3      929
4      930
      ...
395    630
396    635
397    638
398    640
399    642
Name: co2ppm, Length: 400, dtype: int64

In [10]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [11]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
model.predict(x)

array([810.53875057, 810.53875057, 845.5953586 , 863.12366262,
       863.12366262, 845.5953586 , 845.5953586 , 845.5953586 ,
       845.5953586 , 887.99238443, 887.99238443, 873.86004249,
       670.31231842, 617.72740637, 705.36892646, 722.89723048,
       757.95383851, 757.95383851, 757.95383851, 757.95383851,
       740.42553449, 775.48214253, 757.95383851, 722.89723048,
       722.89723048, 722.89723048, 635.25571039, 640.51420159,
       638.76137119, 640.51420159, 637.00854079, 638.76137119,
       637.00854079, 638.76137119, 642.26703199, 640.51420159,
       637.00854079, 647.5255232 , 640.40450286, 654.53684481,
       656.28967521, 656.28967521, 666.80665762, 673.81797923,
       673.81797923, 673.81797923, 661.43846768, 673.81797923,
       673.81797923, 675.57080963, 677.32364003, 677.32364003,
       682.58213123, 691.34628324, 691.34628324, 691.34628324,
       691.34628324, 691.34628324, 689.59345284, 691.34628324,
       691.34628324, 693.09911364, 693.09911364, 693.09911364,
       694.85194405, 694.85194405, 686.08779204, 668.55948802,
       665.05382722, 659.79533601, 679.18616916, 652.7840144 ,
       647.5255232 , 661.65786514, 654.64654353, 651.14088273,
       651.14088273, 635.25571039, 626.49155838, 633.50287998,
       637.00854079, 635.25571039, 635.25571039, 635.25571039,
       629.99721918, 631.75004958, 617.72740637, 619.48023677,
       607.21042396, 610.71608476, 603.70476315, 603.70476315,
       605.45759355, 608.96325436, 631.85974831, 622.98589757,
       621.23306717, 629.99721918, 615.86487724, 629.99721918,
       624.73872797, 622.98589757, 621.23306717, 615.97457597,
       617.72740637, 619.48023677, 615.97457597, 615.97457597,
       610.71608476, 614.22174556, 610.71608476, 610.71608476,
       605.45759355, 608.96325436, 628.24438878, 638.76137119,
       640.51420159, 656.28967521, 691.34628324, 700.00073652,
       658.04250561, 658.04250561, 682.58213123, 593.18778074,
       596.69344155, 598.44627195, 584.42362873, 547.6141903 ,
       558.13117271, 544.67802318, 530.65537996, 518.38556715,
       518.38556715, 520.47799376, 548.18368398, 560.793093  ,
       559.37985881, 613.71760126, 620.72892287, 625.64781787,
       617.22326207, 615.47043167, 631.24590528, 631.24590528,
       641.76288769, 645.2685485 , 647.36097511, 641.76288769,
       641.08369528, 641.08369528, 660.3648297 , 664.21008671,
       665.6233209 , 679.98556032, 683.83081734, 683.83081734,
       704.52518595, 716.79499876, 713.62893417, 710.12327336,
       685.58364774, 699.26669474, 697.51386434, 689.08930854,
       689.08930854, 687.33647814, 686.99688193, 676.47989952,
       676.47989952, 685.24405153, 673.31383493, 660.70442591,
       651.9402739 , 651.9402739 , 653.6931043 , 662.45725631,
       650.18744349, 644.92895229, 641.42329149, 622.53660264,
       610.94598224, 609.19315184, 567.12522219, 574.47614001,
       576.22897041, 566.05158421, 522.23082416, 520.47799376,
       528.90254956, 620.04973046, 650.18744349, 650.18744349,
       601.10819224, 583.91948443, 585.67231484, 589.17797564,
       583.57988823, 573.06290582, 574.81573622, 600.76859604,
       606.02708724, 588.15918702, 589.91201742, 586.40635661,
       647.41582447, 649.16865487, 654.42714608, 673.7082805 ,
       682.47243251, 680.7196021 , 680.7196021 , 689.48375411,
       700.00073652, 704.91963152, 743.82149657, 755.75171317,
       755.75171317, 752.24605237, 622.53660264, 631.30075465,
       631.30075465, 582.2215034 , 596.24414661, 597.99697701,
       589.232825  , 592.73848581, 594.49131621, 578.71584259,
       569.95169058, 569.95169058, 605.00829862, 615.52528103,
       617.27811143, 619.03094183, 631.30075465, 648.82905866,
       655.84038027, 664.60453228, 682.1328363 , 690.89698831,
       687.3913275 , 687.3913275 , 701.41397072, 613.77245063,
       606.76112902, 587.4799946 , 596.24414661, 599.41021121,
       643.57056746, 631.30075465, 634.80641545, 616.93851522,
       608.51395942, 608.51395942, 536.30831674, 546.82529915,
       567.85926397, 569.61209438, 554.17621697, 580.46867299,
       545.41206496, 552.08379036, 619.03094183, 608.17436322,
       620.78377224, 622.53660264, 644.98380165, 662.51210567,
       667.77059688, 674.78191848, 702.82720491, 704.58003531,
       762.42343857, 757.16494737, 753.65928656, 760.67060817,
       762.42343857, 764.17626898, 772.94042098, 702.82720491,
       702.82720491, 694.0630529 , 685.29890089, 678.28757929,
       641.81773706, 650.24229286, 653.74795366, 653.74795366,
       655.50078406, 627.45549763, 629.20832804, 629.20832804,
       571.36492478, 580.12907679, 597.6573808 , 615.18568482,
       613.43285442, 616.93851522, 616.93851522, 620.44417603,
       562.60077277, 555.24985495, 560.84794237, 562.26117656,
       572.77815897, 586.80080219, 588.55363259, 574.53098937,
       564.01400696, 599.070615  , 600.8234454 , 590.30646299,
       616.59891902, 613.09325821, 662.51210567, 669.52342728,
       674.78191848, 701.41397072, 704.91963152, 648.82905866,
       655.84038027, 638.65167246, 638.65167246, 633.05358505,
       736.47057875, 733.30451416, 740.65543197, 782.72336162,
       786.22902242, 796.74600483, 812.52147845, 814.27430885,
       814.27430885, 751.17241438, 749.41958398, 747.66675358,
       740.99502818, 724.87995836, 733.64411037, 716.11580635,
       718.20823296, 705.59882394, 697.17426814, 697.17426814,
       688.07051992, 679.30636791, 681.05919831, 681.05919831,
       667.0365551 , 663.53089429, 665.6233209 , 644.24975987,
       647.75542068, 625.30822166, 618.29690005, 592.00444403,
       593.75727443, 593.75727443, 564.29875381, 573.06290582,
       571.31007541, 568.14401082, 519.06475957, 520.81758997,
       554.1213676 , 559.37985881, 547.110046  , 545.35721559,
       571.64967162, 573.40250202, 606.70627966, 608.45911006,
       641.76288769, 629.83267109, 621.06851908, 625.98741408,
       606.70627966, 598.28172386, 592.68363644, 592.68363644,
       589.17797564, 571.64967162, 578.66099323, 550.95530301,
       552.3685372 , 554.1213676 , 562.88551961, 592.34404023,
       608.11951385, 611.62517465, 615.13083546, 643.17612189,
       650.18744349, 660.70442591, 662.45725631, 676.47989952,
       686.99688193, 695.76103394, 644.92895229, 639.67046108])

In [15]:
model.score(x,y)

0.9321867223303033